### DISCUSSION TITLE
ERROR Authentication failed, status code: 403

### DISCUSSION THREAD

**Discussion by KJ-Waller** [martabal/qbittorrent-exporter#99] [General]
I'm trying to setup this using docker-compose. I have my own .env file with my username, password, and server's local IP.

```
  qbittorrent-exporter:
    image: ghcr.io/martabal/qbittorrent-exporter:latest
    container_name: qbittorrent-exporter
    environment:
      - QBITTORRENT_BASE_URL=http://${LOCAL_IP}:8080
      - QBITTORRENT_PASSWORD='${QBITTORRENT_PASSWORD}'
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
    ports:
      - 8090:8090
    networks:
      - bridge
    restart: unless-stopped
```
However, the `docker logs qbittorrent-exporter` command shows the error `ERROR Authentication failed, status code: 403`. I think it might be because my password contains some special characters, because the values are definitely correct. I tried escaping the special characters using `\` but I can't get it to work. I could try and change my password but wanted to post first to see if it might be another problem, as I'd have to change my password in for my entire stack if I do decide to change it.
